<a href="https://colab.research.google.com/github/RohanKJoseph/IPRS_Tasks/blob/main/Task3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Preparing Medical Appointment Data for Analysis

In [1]:
#importing the required libraries
import pandas as pd
import numpy as np

In [10]:
#connecting with the dataset from kaggle
df = pd.read_csv("/content/KaggleV2-May-2016.csv")
print(df.head()) #for check the connectivity

      PatientId  AppointmentID Gender          ScheduledDay  \
0  2.987250e+13        5642903      F  2016-04-29T18:38:08Z
1  5.589978e+14        5642503      M  2016-04-29T16:08:27Z
2  4.262962e+12        5642549      F  2016-04-29T16:19:04Z
3  8.679512e+11        5642828      F  2016-04-29T17:29:31Z
4  8.841186e+12        5642494      F  2016-04-29T16:07:23Z

         AppointmentDay  Age      Neighbourhood  Scholarship  Hipertension  \
0  2016-04-29T00:00:00Z   62    JARDIM DA PENHA            0             1
1  2016-04-29T00:00:00Z   56    JARDIM DA PENHA            0             0
2  2016-04-29T00:00:00Z   62      MATA DA PRAIA            0             0
3  2016-04-29T00:00:00Z    8  PONTAL DE CAMBURI            0             0
4  2016-04-29T00:00:00Z   56    JARDIM DA PENHA            0             1

   Diabetes  Alcoholism  Handcap  SMS_received No-show
0         0           0        0             0      No
1         0           0        0             0      No
2         0           0        0             0      No
3         0           0        0             0      No
4         1           0        0             0      No

##Inspecting the dataset

In [11]:
df.head() #reading the first 5 rows

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No

In [16]:
print("Rows and Columns:", df.shape) #checking its dimention
print("\n")
df.info() #checking its information

Rows and Columns: (110527, 14)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PatientId       110527 non-null  float64
 1   AppointmentID   110527 non-null  int64
 2   Gender          110527 non-null  object
 3   ScheduledDay    110527 non-null  object
 4   AppointmentDay  110527 non-null  object
 5   Age             110527 non-null  int64
 6   Neighbourhood   110527 non-null  object
 7   Scholarship     110527 non-null  int64
 8   Hipertension    110527 non-null  int64
 9   Diabetes        110527 non-null  int64
 10  Alcoholism      110527 non-null  int64
 11  Handcap         110527 non-null  int64
 12  SMS_received    110527 non-null  int64
 13  No-show         110527 non-null  object
dtypes: float64(1), int64(8), object(5)
memory usage: 11.8+ MB


The datatypes are :

PatientId         float64
AppointmentID       int64
Gender             object
ScheduledDay       object
AppointmentDay     object
Age                 int64
Neighbourhood      object
Scholarship         int64
Hipertension        int64
Diabetes            int64
Alcoholism          int64
Handcap             int64
SMS_received        int64
No-show            object
dtype: object

In [17]:
print("The datatypes are :\n")
print(df.dtypes)

The datatypes are :

PatientId         float64
AppointmentID       int64
Gender             object
ScheduledDay       object
AppointmentDay     object
Age                 int64
Neighbourhood      object
Scholarship         int64
Hipertension        int64
Diabetes            int64
Alcoholism          int64
Handcap             int64
SMS_received        int64
No-show            object
dtype: object

##Data prepration

In [21]:
 #first checking for the missing values
missing = (df.isnull().sum()/len(df))*100
print(missing)

#from the output we can see that there is no missing values

PatientId         0.0
AppointmentID     0.0
Gender            0.0
ScheduledDay      0.0
AppointmentDay    0.0
Age               0.0
Neighbourhood     0.0
Scholarship       0.0
Hipertension      0.0
Diabetes          0.0
Alcoholism        0.0
Handcap           0.0
SMS_received      0.0
No-show           0.0
dtype: float64

##Exploring numerical features

In [25]:
df.describe(include='all') #describing the statistical data

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
count,1.105270e+05,1.105270e+05,110527,110527,110527,110527.000000,110527,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000,110527
unique,NaN,NaN,2,103549,27,NaN,81,NaN,NaN,NaN,NaN,NaN,NaN,2
top,NaN,NaN,F,2016-05-06T07:09:54Z,2016-06-06T00:00:00Z,NaN,JARDIM CAMBURI,NaN,NaN,NaN,NaN,NaN,NaN,No
freq,NaN,NaN,71840,24,4692,NaN,7717,NaN,NaN,NaN,NaN,NaN,NaN,88208
mean,1.474963e+14,5.675305e+06,NaN,NaN,NaN,37.088874,NaN,0.098266,0.197246,0.071865,0.030400,0.022248,0.321026,NaN
std,2.560949e+14,7.129575e+04,NaN,NaN,NaN,23.110205,NaN,0.297675,0.397921,0.258265,0.171686,0.161543,0.466873,NaN
min,3.921784e+04,5.030230e+06,NaN,NaN,NaN,-1.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
25%,4.172614e+12,5.640286e+06,NaN,NaN,NaN,18.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
50%,3.173184e+13,5.680573e+06,NaN,NaN,NaN,37.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
75%,9.439172e+13,5.725524e+06,NaN,NaN,NaN,55.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,NaN
max,9.999816e+14,5.790484e+06,NaN,NaN,NaN,115.000000,NaN,1.000000,1.000000,1.000000,1.000000,4.000000,1.000000,NaN

In [22]:
#Displaying summary statistics
for col in df.select_dtypes(include=['int64','float64']).columns:
    print("\n", col)
    print(df[col].describe())

 PatientId
count    1.105270e+05
mean     1.474963e+14
std      2.560949e+14
min      3.921784e+04
25%      4.172614e+12
50%      3.173184e+13
75%      9.439172e+13
max      9.999816e+14
Name: PatientId, dtype: float64

 AppointmentID
count    1.105270e+05
mean     5.675305e+06
std      7.129575e+04
min      5.030230e+06
25%      5.640286e+06
50%      5.680573e+06
75%      5.725524e+06
max      5.790484e+06
Name: AppointmentID, dtype: float64

 Age
count    110527.000000
mean         37.088874
std          23.110205
min          -1.000000
25%          18.000000
50%          37.000000
75%          55.000000
max         115.000000
Name: Age, dtype: float64

 Scholarship
count    110527.000000
mean          0.098266
std           0.297675
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: Scholarship, dtype: float64

 Hipertension
count    110527.000000
mean          0.197246
std           0.397921
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: Hipertension, dtype: float64

 Diabetes
count    110527.000000
mean          0.071865
std           0.258265
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: Diabetes, dtype: float64

 Alcoholism
count    110527.000000
mean          0.030400
std           0.171686
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: Alcoholism, dtype: float64

 Handcap
count    110527.000000
mean          0.022248
std           0.161543
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           4.000000
Name: Handcap, dtype: float64

 SMS_received
count    110527.000000
mean          0.321026
std           0.466873
min           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
max           1.000000
Name: SMS_received, dtype: float64

##Converting categorical variables into numerical form (**encoding**)

In [28]:
#converting the date to a numeric value finding the waiting time
#which is by subtracting the AppointmentDay from ScheduledDay
df['ScheduledDay'] = pd.to_datetime(df['ScheduledDay'])
df['AppointmentDay'] = pd.to_datetime(df['AppointmentDay'])

df['WaitingDays'] = (
    df['AppointmentDay'] - df['ScheduledDay']
).dt.days

# print(df.WaitingDays)

0         -1
1         -1
2         -1
3         -1
4         -1
          ..
110522    34
110523    34
110524    40
110525    40
110526    40
Name: WaitingDays, Length: 110527, dtype: int64

In [29]:
#Encode Categorical Variables

df.select_dtypes(include='object').columns #Identify Categorical Columns

Index(['Gender', 'Neighbourhood', 'No-show'], dtype='object')

In [30]:
#1 Label encoding for columns like Gender and No-Show
#as we can use binary variables

df['Gender'] = df['Gender'].map({'F':0, 'M':1})
df['No-show'] = df['No-show'].map({'No':1, 'Yes':0})

In [31]:
#2 One- hot encoding for multy catagory columns like Neighbourhood

df = pd.get_dummies(df,columns=['Neighbourhood'],drop_first=True)

In [39]:
#checking the values of age
print(df['Age'].min())
print(df['Age'].max())

#removing the invalid ages
df = df[df['Age'] >= 0]

print(df['Age'].min())  #now the age is varified

0
115
0

In [46]:
#Check Binary Medical Condition Columns

binary_cols = [
    'Scholarship',
    'Hipertension',
    'Diabetes',
    'Alcoholism',
    'Handcap',
    'SMS_received'
]

for col in binary_cols:
    print(col, df[col].unique())

Scholarship [0 1]
Hipertension [1 0]
Diabetes [0 1]
Alcoholism [0 1]
Handcap [0 1 2 3 4]
SMS_received [0 1]

##Final validation

In [41]:
print(df.info()) #checking all the information about the data , its in the clean format for further use

<class 'pandas.core.frame.DataFrame'>
Index: 110526 entries, 0 to 110526
Data columns (total 94 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   PatientId                                  110526 non-null  float64
 1   AppointmentID                              110526 non-null  int64
 2   Gender                                     110526 non-null  int64
 3   ScheduledDay                               110526 non-null  datetime64[ns, UTC]
 4   AppointmentDay                             110526 non-null  datetime64[ns, UTC]
 5   Age                                        110526 non-null  int64
 6   Scholarship                                110526 non-null  int64
 7   Hipertension                               110526 non-null  int64
 8   Diabetes                                   110526 non-null  int64
 9   Alcoholism                                 110526 non-null  int64
 10  Handcap                                    110526 non-null  int64
 11  SMS_received                               110526 non-null  int64
 12  No-show                                    110526 non-null  int64
 13  WaitingDays                                110526 non-null  int64
 14  Neighbourhood_ANDORINHAS                   110526 non-null  bool
 15  Neighbourhood_ANTÔNIO HONÓRIO              110526 non-null  bool
 16  Neighbourhood_ARIOVALDO FAVALESSA          110526 non-null  bool
 17  Neighbourhood_BARRO VERMELHO               110526 non-null  bool
 18  Neighbourhood_BELA VISTA                   110526 non-null  bool
 19  Neighbourhood_BENTO FERREIRA               110526 non-null  bool
 20  Neighbourhood_BOA VISTA                    110526 non-null  bool
 21  Neighbourhood_BONFIM                       110526 non-null  bool
 22  Neighbourhood_CARATOÍRA                    110526 non-null  bool
 23  Neighbourhood_CENTRO                       110526 non-null  bool
 24  Neighbourhood_COMDUSA                      110526 non-null  bool
 25  Neighbourhood_CONQUISTA                    110526 non-null  bool
 26  Neighbourhood_CONSOLAÇÃO                   110526 non-null  bool
 27  Neighbourhood_CRUZAMENTO                   110526 non-null  bool
 28  Neighbourhood_DA PENHA                     110526 non-null  bool
 29  Neighbourhood_DE LOURDES                   110526 non-null  bool
 30  Neighbourhood_DO CABRAL                    110526 non-null  bool
 31  Neighbourhood_DO MOSCOSO                   110526 non-null  bool
 32  Neighbourhood_DO QUADRO                    110526 non-null  bool
 33  Neighbourhood_ENSEADA DO SUÁ               110526 non-null  bool
 34  Neighbourhood_ESTRELINHA                   110526 non-null  bool
 35  Neighbourhood_FONTE GRANDE                 110526 non-null  bool
 36  Neighbourhood_FORTE SÃO JOÃO               110526 non-null  bool
 37  Neighbourhood_FRADINHOS                    110526 non-null  bool
 38  Neighbourhood_GOIABEIRAS                   110526 non-null  bool
 39  Neighbourhood_GRANDE VITÓRIA               110526 non-null  bool
 40  Neighbourhood_GURIGICA                     110526 non-null  bool
 41  Neighbourhood_HORTO                        110526 non-null  bool
 42  Neighbourhood_ILHA DAS CAIEIRAS            110526 non-null  bool
 43  Neighbourhood_ILHA DE SANTA MARIA          110526 non-null  bool
 44  Neighbourhood_ILHA DO BOI                  110526 non-null  bool
 45  Neighbourhood_ILHA DO FRADE                110526 non-null  bool
 46  Neighbourhood_ILHA DO PRÍNCIPE             110526 non-null  bool
 47  Neighbourhood_ILHAS OCEÂNICAS DE TRINDADE  110526 non-null  bool
 48  Neighbourhood_INHANGUETÁ                   110526 non-null  bool
 49  Neighbourhood_ITARARÉ                      110526 non-null  bool
 50  Neighbourhood_JABOUR                       110526 non-null  bool
 51  Neighbourhood_JARDIM CAMBURI               110526 non-null  bool
 52  Neighbourhood_JARDIM DA PENHA              110526 non-null  bool
 53  Neighbourhood_JESUS DE NAZARETH            110526 non-null  bool
 54  Neighbourhood_JOANA D´ARC                  110526 non-null  bool
 55  Neighbourhood_JUCUTUQUARA                  110526 non-null  bool
 56  Neighbourhood_MARIA ORTIZ                  110526 non-null  bool
 57  Neighbourhood_MARUÍPE                      110526 non-null  bool
 58  Neighbourhood_MATA DA PRAIA                110526 non-null  bool
 59  Neighbourhood_MONTE BELO                   110526 non-null  bool
 60  Neighbourhood_MORADA DE CAMBURI            110526 non-null  bool
 61  Neighbourhood_MÁRIO CYPRESTE               110526 non-null  bool
 62  Neighbourhood_NAZARETH                     110526 non-null  bool
 63  Neighbourhood_NOVA PALESTINA               110526 non-null  bool
 64  Neighbourhood_PARQUE INDUSTRIAL            110526 non-null  bool
 65  Neighbourhood_PARQUE MOSCOSO               110526 non-null  bool
 66  Neighbourhood_PIEDADE                      110526 non-null  bool
 67  Neighbourhood_PONTAL DE CAMBURI            110526 non-null  bool
 68  Neighbourhood_PRAIA DO CANTO               110526 non-null  bool
 69  Neighbourhood_PRAIA DO SUÁ                 110526 non-null  bool
 70  Neighbourhood_REDENÇÃO                     110526 non-null  bool
 71  Neighbourhood_REPÚBLICA                    110526 non-null  bool
 72  Neighbourhood_RESISTÊNCIA                  110526 non-null  bool
 73  Neighbourhood_ROMÃO                        110526 non-null  bool
 74  Neighbourhood_SANTA CECÍLIA                110526 non-null  bool
 75  Neighbourhood_SANTA CLARA                  110526 non-null  bool
 76  Neighbourhood_SANTA HELENA                 110526 non-null  bool
 77  Neighbourhood_SANTA LUÍZA                  110526 non-null  bool
 78  Neighbourhood_SANTA LÚCIA                  110526 non-null  bool
 79  Neighbourhood_SANTA MARTHA                 110526 non-null  bool
 80  Neighbourhood_SANTA TEREZA                 110526 non-null  bool
 81  Neighbourhood_SANTO ANDRÉ                  110526 non-null  bool
 82  Neighbourhood_SANTO ANTÔNIO                110526 non-null  bool
 83  Neighbourhood_SANTOS DUMONT                110526 non-null  bool
 84  Neighbourhood_SANTOS REIS                  110526 non-null  bool
 85  Neighbourhood_SEGURANÇA DO LAR             110526 non-null  bool
 86  Neighbourhood_SOLON BORGES                 110526 non-null  bool
 87  Neighbourhood_SÃO BENEDITO                 110526 non-null  bool
 88  Neighbourhood_SÃO CRISTÓVÃO                110526 non-null  bool
 89  Neighbourhood_SÃO JOSÉ                     110526 non-null  bool
 90  Neighbourhood_SÃO PEDRO                    110526 non-null  bool
 91  Neighbourhood_TABUAZEIRO                   110526 non-null  bool
 92  Neighbourhood_UNIVERSITÁRIO                110526 non-null  bool
 93  Neighbourhood_VILA RUBIM                   110526 non-null  bool
dtypes: bool(80), datetime64[ns, UTC](2), float64(1), int64(11)
memory usage: 21.1 MB
None

In [45]:
print(df.isnull().sum()) #checking for missing values, all are filled

PatientId                      0
AppointmentID                  0
Gender                         0
ScheduledDay                   0
AppointmentDay                 0
                              ..
Neighbourhood_SÃO JOSÉ         0
Neighbourhood_SÃO PEDRO        0
Neighbourhood_TABUAZEIRO       0
Neighbourhood_UNIVERSITÁRIO    0
Neighbourhood_VILA RUBIM       0
Length: 94, dtype: int64

In [44]:
print(df.describe()) #describing the data set

          PatientId  AppointmentID         Gender            Age  \
count  1.105260e+05   1.105260e+05  110526.000000  110526.000000
mean   1.474934e+14   5.675304e+06       0.350026      37.089219
std    2.560943e+14   7.129544e+04       0.476980      23.110026
min    3.921784e+04   5.030230e+06       0.000000       0.000000
25%    4.172536e+12   5.640285e+06       0.000000      18.000000
50%    3.173184e+13   5.680572e+06       0.000000      37.000000
75%    9.438963e+13   5.725523e+06       1.000000      55.000000
max    9.999816e+14   5.790484e+06       1.000000     115.000000

         Scholarship   Hipertension       Diabetes     Alcoholism  \
count  110526.000000  110526.000000  110526.000000  110526.000000
mean        0.098266       0.197248       0.071865       0.030400
std         0.297676       0.397923       0.258266       0.171686
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000       0.000000
50%         0.000000       0.000000       0.000000       0.000000
75%         0.000000       0.000000       0.000000       0.000000
max         1.000000       1.000000       1.000000       1.000000

             Handcap   SMS_received        No-show    WaitingDays
count  110526.000000  110526.000000  110526.000000  110526.000000
mean        0.022248       0.321029       0.798066       9.183794
std         0.161543       0.466874       0.401445      15.255034
min         0.000000       0.000000       0.000000      -7.000000
25%         0.000000       0.000000       1.000000      -1.000000
50%         0.000000       0.000000       1.000000       3.000000
75%         0.000000       1.000000       1.000000      14.000000
max         4.000000       1.000000       1.000000     178.000000